// TODO: Insert description here. (generated by smylabathula)

#include <iostream>
#include <vector>
#include <stdlib.h>
#include "MotionModel.h"
using namespace std;

int main() {
  MotionModel mm;
  mm.load("jump.txt");
  mm.print();
  return 0;
}




